# Generated by Django 3.2 on 2023-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('individual_class', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
